INSERT INTO product (name,category,material,size,gender,price,img1,qty,description,store_id)
VALUES('black necklace','necklaces','wood','medium','female',112.99,'images/Default_Pic.png',10,'Duis id malesuada augue. Nam mi erat, pretium sit amet tempor in, ultrices at augue. Sed aliquet pulvinar dignissim. Morbi bibendum sem eu nulla semper non vehicula nulla interdum. Aliquam sodales arcu in nibh ullamcorper hendrerit. Curabitur facilisis mauris id arcu volutpat congue. Nulla sit amet odio orci, quis lacinia leo. Vestibulum vel lobortis mauris. ', 1);

INSERT INTO product (name,category,material,size,gender,price,img1,qty,description,store_id)
VALUES('white necklace','necklaces','silver','medium','unisex',8.99,'images/Default_Pic.png',10,'Nulla aliquet fermentum tortor nec semper. Sed justo ipsum, vehicula sed lacinia vitae, vulputate sed est. Nunc tristique quam congue neque ultricies mattis. Nunc leo sapien, porttitor quis vehicula non, bibendum sed mauris. Etiam sed lorem nisl. Nunc consectetur vestibulum tristique. Maecenas ut eros neque. Vestibulum luctus eros sed tortor commodo faucibus. Curabitur nec rhoncus turpis. Nunc aliquet interdum leo, ac tempus nisl convallis at. Phasellus sit amet velit ante.', 1);

INSERT INTO product (name,category,material,size,gender,price,img1,qty,description,store_id)
VALUES('green necklace','necklaces','silver','medium','female',2.99,'images/Default_Pic.png',10,'Mauris porttitor ipsum in quam interdum imperdiet. Sed enim risus, sodales in pellentesque eget, sagittis sit amet mi. Phasellus at mollis dolor. Etiam turpis nunc, suscipit eget tincidunt aliquet, accumsan non lectus. Nulla facilisi. Phasellus sed lorem quis mauris adipiscing elementum. Donec nec massa ligula. Quisque iaculis nunc sed mi egestas laoreet.', 1);

INSERT INTO product (name,category,material,size,gender,price,img1,qty,description,store_id)
VALUES('blue necklace','necklaces','silver','medium','male',24.99,'images/Default_Pic.png',10,'Nam placerat, elit eu venenatis bibendum, diam turpis consequat eros, eget cursus massa ligula in orci. Sed imperdiet tortor nec dui porta sed pharetra quam aliquam. Pellentesque a nisl lorem. Nunc gravida interdum risus, sit amet tincidunt lacus commodo ac. Suspendisse aliquet odio sed tellus tempor placerat. Etiam hendrerit nisl sit amet neque pulvinar ornare. Maecenas elit justo, elementum ut vestibulum fringilla, accumsan mollis mi. Quisque hendrerit sagittis nisl. Nunc semper porta magna. Aenean suscipit nibh et lorem vestibulum gravid', 1);

INSERT INTO product (name,category,material,size,gender,price,img1,qty,description,store_id)
VALUES('yellow necklace','necklaces','silver','medium','female',112.99,'images/Default_Pic.png',10,'Duis id malesuada augue. Nam mi erat, pretium sit amet tempor in, ultrices at augue. Sed aliquet pulvinar dignissim. Morbi bibendum sem eu nulla semper non vehicula nulla interdum. Aliquam sodales arcu in nibh ullamcorper hendrerit. Curabitur facilisis mauris id arcu volutpat congue. Nulla sit amet odio orci, quis lacinia leo. Vestibulum vel lobortis mauris. ', 1);

INSERT INTO product (name,category,material,size,gender,price,img1,qty,description,store_id)
VALUES('orange necklace','necklaces','silver','medium','unisex',8.99,'images/Default_Pic.png',10,'Nulla aliquet fermentum tortor nec semper. Sed justo ipsum, vehicula sed lacinia vitae, vulputate sed est. Nunc tristique quam congue neque ultricies mattis. Nunc leo sapien, porttitor quis vehicula non, bibendum sed mauris. Etiam sed lorem nisl. Nunc consectetur vestibulum tristique. Maecenas ut eros neque. Vestibulum luctus eros sed tortor commodo faucibus. Curabitur nec rhoncus turpis. Nunc aliquet interdum leo, ac tempus nisl convallis at. Phasellus sit amet velit ante.', 1);

INSERT INTO product (name,category,material,size,gender,price,img1,qty,description,store_id)
VALUES('silver necklace','necklaces','silver','medium','female',2.99,'images/Default_Pic.png',10,'Mauris porttitor ipsum in quam interdum imperdiet. Sed enim risus, sodales in pellentesque eget, sagittis sit amet mi. Phasellus at mollis dolor. Etiam turpis nunc, suscipit eget tincidunt aliquet, accumsan non lectus. Nulla facilisi. Phasellus sed lorem quis mauris adipiscing elementum. Donec nec massa ligula. Quisque iaculis nunc sed mi egestas laoreet.', 1);

INSERT INTO product (name,category,material,size,gender,price,img1,qty,description,store_id)
VALUES('long necklace','necklaces','silver','medium','male',24.99,'images/Default_Pic.png',10,'Nam placerat, elit eu venenatis bibendum, diam turpis consequat eros, eget cursus massa ligula in orci. Sed imperdiet tortor nec dui porta sed pharetra quam aliquam. Pellentesque a nisl lorem. Nunc gravida interdum risus, sit amet tincidunt lacus commodo ac. Suspendisse aliquet odio sed tellus tempor placerat. Etiam hendrerit nisl sit amet neque pulvinar ornare. Maecenas elit justo, elementum ut vestibulum fringilla, accumsan mollis mi. Quisque hendrerit sagittis nisl. Nunc semper porta magna. Aenean suscipit nibh et lorem vestibulum gravid', 1);

INSERT INTO product (name,category,material,size,gender,price,img1,qty,description,store_id)
VALUES('short necklace','necklaces','silver','medium','female',112.99,'images/Default_Pic.png',10,'Duis id malesuada augue. Nam mi erat, pretium sit amet tempor in, ultrices at augue. Sed aliquet pulvinar dignissim. Morbi bibendum sem eu nulla semper non vehicula nulla interdum. Aliquam sodales arcu in nibh ullamcorper hendrerit. Curabitur facilisis mauris id arcu volutpat congue. Nulla sit amet odio orci, quis lacinia leo. Vestibulum vel lobortis mauris. ', 1);

INSERT INTO product (name,category,material,size,gender,price,img1,qty,description,store_id)
VALUES('cat necklace','necklaces','silver','medium','unisex',8.99,'images/Default_Pic.png',10,'Nulla aliquet fermentum tortor nec semper. Sed justo ipsum, vehicula sed lacinia vitae, vulputate sed est. Nunc tristique quam congue neque ultricies mattis. Nunc leo sapien, porttitor quis vehicula non, bibendum sed mauris. Etiam sed lorem nisl. Nunc consectetur vestibulum tristique. Maecenas ut eros neque. Vestibulum luctus eros sed tortor commodo faucibus. Curabitur nec rhoncus turpis. Nunc aliquet interdum leo, ac tempus nisl convallis at. Phasellus sit amet velit ante.', 1);

INSERT INTO product (name,category,material,size,gender,price,img1,qty,description,store_id)
VALUES('dog necklace','necklaces','silver','medium','female',2.99,'images/Default_Pic.png',10,'Mauris porttitor ipsum in quam interdum imperdiet. Sed enim risus, sodales in pellentesque eget, sagittis sit amet mi. Phasellus at mollis dolor. Etiam turpis nunc, suscipit eget tincidunt aliquet, accumsan non lectus. Nulla facilisi. Phasellus sed lorem quis mauris adipiscing elementum. Donec nec massa ligula. Quisque iaculis nunc sed mi egestas laoreet.', 1);

INSERT INTO product (name,category,material,size,gender,price,img1,qty,description,store_id)
VALUES('jetter necklace','necklaces','silver','medium','male',24.99,'images/Default_Pic.png',10,'Nam placerat, elit eu venenatis bibendum, diam turpis consequat eros, eget cursus massa ligula in orci. Sed imperdiet tortor nec dui porta sed pharetra quam aliquam. Pellentesque a nisl lorem. Nunc gravida interdum risus, sit amet tincidunt lacus commodo ac. Suspendisse aliquet odio sed tellus tempor placerat. Etiam hendrerit nisl sit amet neque pulvinar ornare. Maecenas elit justo, elementum ut vestibulum fringilla, accumsan mollis mi. Quisque hendrerit sagittis nisl. Nunc semper porta magna. Aenean suscipit nibh et lorem vestibulum gravid', 1);

INSERT INTO product (name,category,material,size,gender,price,img1,qty,description,store_id)
VALUES('grip necklace','necklaces','silver','medium','female',112.99,'images/Default_Pic.png',10,'Duis id malesuada augue. Nam mi erat, pretium sit amet tempor in, ultrices at augue. Sed aliquet pulvinar dignissim. Morbi bibendum sem eu nulla semper non vehicula nulla interdum. Aliquam sodales arcu in nibh ullamcorper hendrerit. Curabitur facilisis mauris id arcu volutpat congue. Nulla sit amet odio orci, quis lacinia leo. Vestibulum vel lobortis mauris. ', 1);

INSERT INTO product (name,category,material,size,gender,price,img1,qty,description,store_id)
VALUES('hyp necklace','necklaces','silver','medium','unisex',8.99,'images/Default_Pic.png',10,'Nulla aliquet fermentum tortor nec semper. Sed justo ipsum, vehicula sed lacinia vitae, vulputate sed est. Nunc tristique quam congue neque ultricies mattis. Nunc leo sapien, porttitor quis vehicula non, bibendum sed mauris. Etiam sed lorem nisl. Nunc consectetur vestibulum tristique. Maecenas ut eros neque. Vestibulum luctus eros sed tortor commodo faucibus. Curabitur nec rhoncus turpis. Nunc aliquet interdum leo, ac tempus nisl convallis at. Phasellus sit amet velit ante.', 1);

INSERT INTO product (name,category,material,size,gender,price,img1,qty,description,store_id)
VALUES('w23c necklace','necklaces','silver','medium','female',2.99,'images/Default_Pic.png',10,'Mauris porttitor ipsum in quam interdum imperdiet. Sed enim risus, sodales in pellentesque eget, sagittis sit amet mi. Phasellus at mollis dolor. Etiam turpis nunc, suscipit eget tincidunt aliquet, accumsan non lectus. Nulla facilisi. Phasellus sed lorem quis mauris adipiscing elementum. Donec nec massa ligula. Quisque iaculis nunc sed mi egestas laoreet.', 1);

INSERT INTO product (name,category,material,size,gender,price,img1,qty,description,store_id)
VALUES('copper necklace','necklaces','silver','medium','male',24.99,'images/Default_Pic.png',10,'Nam placerat, elit eu venenatis bibendum, diam turpis consequat eros, eget cursus massa ligula in orci. Sed imperdiet tortor nec dui porta sed pharetra quam aliquam. Pellentesque a nisl lorem. Nunc gravida interdum risus, sit amet tincidunt lacus commodo ac. Suspendisse aliquet odio sed tellus tempor placerat. Etiam hendrerit nisl sit amet neque pulvinar ornare. Maecenas elit justo, elementum ut vestibulum fringilla, accumsan mollis mi. Quisque hendrerit sagittis nisl. Nunc semper porta magna. Aenean suscipit nibh et lorem vestibulum gravid', 1);

INSERT INTO product (name,category,material,size,gender,price,img1,qty,description,store_id)
VALUES('necklace for women','necklaces','silver','medium','female',112.99,'images/Default_Pic.png',10,'Duis id malesuada augue. Nam mi erat, pretium sit amet tempor in, ultrices at augue. Sed aliquet pulvinar dignissim. Morbi bibendum sem eu nulla semper non vehicula nulla interdum. Aliquam sodales arcu in nibh ullamcorper hendrerit. Curabitur facilisis mauris id arcu volutpat congue. Nulla sit amet odio orci, quis lacinia leo. Vestibulum vel lobortis mauris. ', 1);

INSERT INTO product (name,category,material,size,gender,price,img1,qty,description,store_id)
VALUES('necklace of time','necklaces','silver','medium','unisex',8.99,'images/Default_Pic.png',10,'Nulla aliquet fermentum tortor nec semper. Sed justo ipsum, vehicula sed lacinia vitae, vulputate sed est. Nunc tristique quam congue neque ultricies mattis. Nunc leo sapien, porttitor quis vehicula non, bibendum sed mauris. Etiam sed lorem nisl. Nunc consectetur vestibulum tristique. Maecenas ut eros neque. Vestibulum luctus eros sed tortor commodo faucibus. Curabitur nec rhoncus turpis. Nunc aliquet interdum leo, ac tempus nisl convallis at. Phasellus sit amet velit ante.', 1);

INSERT INTO product (name,category,material,size,gender,price,img1,qty,description,store_id)
VALUES('black necklace','necklaces','silver','medium','female',2.99,'images/Default_Pic.png',10,'Mauris porttitor ipsum in quam interdum imperdiet. Sed enim risus, sodales in pellentesque eget, sagittis sit amet mi. Phasellus at mollis dolor. Etiam turpis nunc, suscipit eget tincidunt aliquet, accumsan non lectus. Nulla facilisi. Phasellus sed lorem quis mauris adipiscing elementum. Donec nec massa ligula. Quisque iaculis nunc sed mi egestas laoreet.', 1);

INSERT INTO product (name,category,material,size,gender,price,img1,qty,description,store_id)
VALUES('necklace223','necklaces','silver','medium','male',24.99,'images/Default_Pic.png',10,'Nam placerat, elit eu venenatis bibendum, diam turpis consequat eros, eget cursus massa ligula in orci. Sed imperdiet tortor nec dui porta sed pharetra quam aliquam. Pellentesque a nisl lorem. Nunc gravida interdum risus, sit amet tincidunt lacus commodo ac. Suspendisse aliquet odio sed tellus tempor placerat. Etiam hendrerit nisl sit amet neque pulvinar ornare. Maecenas elit justo, elementum ut vestibulum fringilla, accumsan mollis mi. Quisque hendrerit sagittis nisl. Nunc semper porta magna. Aenean suscipit nibh et lorem vestibulum gravid', 1);

INSERT INTO product (name,category,material,size,gender,price,img1,qty,description,store_id)
VALUES('necklace001','necklaces','silver','medium','female',112.99,'images/Default_Pic.png',10,'Duis id malesuada augue. Nam mi erat, pretium sit amet tempor in, ultrices at augue. Sed aliquet pulvinar dignissim. Morbi bibendum sem eu nulla semper non vehicula nulla interdum. Aliquam sodales arcu in nibh ullamcorper hendrerit. Curabitur facilisis mauris id arcu volutpat congue. Nulla sit amet odio orci, quis lacinia leo. Vestibulum vel lobortis mauris. ', 1);

INSERT INTO product (name,category,material,size,gender,price,img1,qty,description,store_id)
VALUES('necklace998','necklaces','silver','medium','unisex',8.99,'images/Default_Pic.png',10,'Nulla aliquet fermentum tortor nec semper. Sed justo ipsum, vehicula sed lacinia vitae, vulputate sed est. Nunc tristique quam congue neque ultricies mattis. Nunc leo sapien, porttitor quis vehicula non, bibendum sed mauris. Etiam sed lorem nisl. Nunc consectetur vestibulum tristique. Maecenas ut eros neque. Vestibulum luctus eros sed tortor commodo faucibus. Curabitur nec rhoncus turpis. Nunc aliquet interdum leo, ac tempus nisl convallis at. Phasellus sit amet velit ante.', 1);

INSERT INTO product (name,category,material,size,gender,price,img1,qty,description,store_id)
VALUES('necklace234','necklaces','silver','medium','female',2.99,'images/Default_Pic.png',10,'Mauris porttitor ipsum in quam interdum imperdiet. Sed enim risus, sodales in pellentesque eget, sagittis sit amet mi. Phasellus at mollis dolor. Etiam turpis nunc, suscipit eget tincidunt aliquet, accumsan non lectus. Nulla facilisi. Phasellus sed lorem quis mauris adipiscing elementum. Donec nec massa ligula. Quisque iaculis nunc sed mi egestas laoreet.', 1);

INSERT INTO product (name,category,material,size,gender,price,img1,qty,description,store_id)
VALUES('necklace544','necklaces','silver','medium','male',24.99,'images/Default_Pic.png',10,'Nam placerat, elit eu venenatis bibendum, diam turpis consequat eros, eget cursus massa ligula in orci. Sed imperdiet tortor nec dui porta sed pharetra quam aliquam. Pellentesque a nisl lorem. Nunc gravida interdum risus, sit amet tincidunt lacus commodo ac. Suspendisse aliquet odio sed tellus tempor placerat. Etiam hendrerit nisl sit amet neque pulvinar ornare. Maecenas elit justo, elementum ut vestibulum fringilla, accumsan mollis mi. Quisque hendrerit sagittis nisl. Nunc semper porta magna. Aenean suscipit nibh et lorem vestibulum gravid', 1);

INSERT INTO product (name,category,material,size,gender,price,img1,qty,description,store_id)
VALUES('black ring','rings','wood','medium','female',112.99,'images/Default_Pic.png',10,'Duis id malesuada augue. Nam mi erat, pretium sit amet tempor in, ultrices at augue. Sed aliquet pulvinar dignissim. Morbi bibendum sem eu nulla semper non vehicula nulla interdum. Aliquam sodales arcu in nibh ullamcorper hendrerit. Curabitur facilisis mauris id arcu volutpat congue. Nulla sit amet odio orci, quis lacinia leo. Vestibulum vel lobortis mauris. ', 2);

INSERT INTO product (name,category,material,size,gender,price,img1,qty,description,store_id)
VALUES('white ring','rings','silver','medium','unisex',8.99,'images/Default_Pic.png',10,'Nulla aliquet fermentum tortor nec semper. Sed justo ipsum, vehicula sed lacinia vitae, vulputate sed est. Nunc tristique quam congue neque ultricies mattis. Nunc leo sapien, porttitor quis vehicula non, bibendum sed mauris. Etiam sed lorem nisl. Nunc consectetur vestibulum tristique. Maecenas ut eros neque. Vestibulum luctus eros sed tortor commodo faucibus. Curabitur nec rhoncus turpis. Nunc aliquet interdum leo, ac tempus nisl convallis at. Phasellus sit amet velit ante.', 2);

INSERT INTO product (name,category,material,size,gender,price,img1,qty,description,store_id)
VALUES('green ring','rings','silver','medium','female',2.99,'images/Default_Pic.png',10,'Mauris porttitor ipsum in quam interdum imperdiet. Sed enim risus, sodales in pellentesque eget, sagittis sit amet mi. Phasellus at mollis dolor. Etiam turpis nunc, suscipit eget tincidunt aliquet, accumsan non lectus. Nulla facilisi. Phasellus sed lorem quis mauris adipiscing elementum. Donec nec massa ligula. Quisque iaculis nunc sed mi egestas laoreet.', 2);

INSERT INTO product (name,category,material,size,gender,price,img1,qty,description,store_id)
VALUES('blue ring','rings','silver','medium','male',24.99,'images/Default_Pic.png',10,'Nam placerat, elit eu venenatis bibendum, diam turpis consequat eros, eget cursus massa ligula in orci. Sed imperdiet tortor nec dui porta sed pharetra quam aliquam. Pellentesque a nisl lorem. Nunc gravida interdum risus, sit amet tincidunt lacus commodo ac. Suspendisse aliquet odio sed tellus tempor placerat. Etiam hendrerit nisl sit amet neque pulvinar ornare. Maecenas elit justo, elementum ut vestibulum fringilla, accumsan mollis mi. Quisque hendrerit sagittis nisl. Nunc semper porta magna. Aenean suscipit nibh et lorem vestibulum gravid', 2);

INSERT INTO product (name,category,material,size,gender,price,img1,qty,description,store_id)
VALUES('yellow ring','rings','silver','medium','female',112.99,'images/Default_Pic.png',10,'Duis id malesuada augue. Nam mi erat, pretium sit amet tempor in, ultrices at augue. Sed aliquet pulvinar dignissim. Morbi bibendum sem eu nulla semper non vehicula nulla interdum. Aliquam sodales arcu in nibh ullamcorper hendrerit. Curabitur facilisis mauris id arcu volutpat congue. Nulla sit amet odio orci, quis lacinia leo. Vestibulum vel lobortis mauris. ', 2);

INSERT INTO product (name,category,material,size,gender,price,img1,qty,description,store_id)
VALUES('orange ring','rings','silver','medium','unisex',8.99,'images/Default_Pic.png',10,'Nulla aliquet fermentum tortor nec semper. Sed justo ipsum, vehicula sed lacinia vitae, vulputate sed est. Nunc tristique quam congue neque ultricies mattis. Nunc leo sapien, porttitor quis vehicula non, bibendum sed mauris. Etiam sed lorem nisl. Nunc consectetur vestibulum tristique. Maecenas ut eros neque. Vestibulum luctus eros sed tortor commodo faucibus. Curabitur nec rhoncus turpis. Nunc aliquet interdum leo, ac tempus nisl convallis at. Phasellus sit amet velit ante.', 2);

INSERT INTO product (name,category,material,size,gender,price,img1,qty,description,store_id)
VALUES('silver ring','rings','silver','medium','female',2.99,'images/Default_Pic.png',10,'Mauris porttitor ipsum in quam interdum imperdiet. Sed enim risus, sodales in pellentesque eget, sagittis sit amet mi. Phasellus at mollis dolor. Etiam turpis nunc, suscipit eget tincidunt aliquet, accumsan non lectus. Nulla facilisi. Phasellus sed lorem quis mauris adipiscing elementum. Donec nec massa ligula. Quisque iaculis nunc sed mi egestas laoreet.', 2);

INSERT INTO product (name,category,material,size,gender,price,img1,qty,description,store_id)
VALUES('long ring','rings','silver','medium','male',24.99,'images/Default_Pic.png',10,'Nam placerat, elit eu venenatis bibendum, diam turpis consequat eros, eget cursus massa ligula in orci. Sed imperdiet tortor nec dui porta sed pharetra quam aliquam. Pellentesque a nisl lorem. Nunc gravida interdum risus, sit amet tincidunt lacus commodo ac. Suspendisse aliquet odio sed tellus tempor placerat. Etiam hendrerit nisl sit amet neque pulvinar ornare. Maecenas elit justo, elementum ut vestibulum fringilla, accumsan mollis mi. Quisque hendrerit sagittis nisl. Nunc semper porta magna. Aenean suscipit nibh et lorem vestibulum gravid', 2);

INSERT INTO product (name,category,material,size,gender,price,img1,qty,description,store_id)
VALUES('short ring','rings','silver','medium','female',112.99,'images/Default_Pic.png',10,'Duis id malesuada augue. Nam mi erat, pretium sit amet tempor in, ultrices at augue. Sed aliquet pulvinar dignissim. Morbi bibendum sem eu nulla semper non vehicula nulla interdum. Aliquam sodales arcu in nibh ullamcorper hendrerit. Curabitur facilisis mauris id arcu volutpat congue. Nulla sit amet odio orci, quis lacinia leo. Vestibulum vel lobortis mauris. ', 2);

INSERT INTO product (name,category,material,size,gender,price,img1,qty,description,store_id)
VALUES('cat ring','rings','silver','medium','unisex',8.99,'images/Default_Pic.png',10,'Nulla aliquet fermentum tortor nec semper. Sed justo ipsum, vehicula sed lacinia vitae, vulputate sed est. Nunc tristique quam congue neque ultricies mattis. Nunc leo sapien, porttitor quis vehicula non, bibendum sed mauris. Etiam sed lorem nisl. Nunc consectetur vestibulum tristique. Maecenas ut eros neque. Vestibulum luctus eros sed tortor commodo faucibus. Curabitur nec rhoncus turpis. Nunc aliquet interdum leo, ac tempus nisl convallis at. Phasellus sit amet velit ante.', 2);

INSERT INTO product (name,category,material,size,gender,price,img1,qty,description,store_id)
VALUES('dog ring','rings','silver','medium','female',2.99,'images/Default_Pic.png',10,'Mauris porttitor ipsum in quam interdum imperdiet. Sed enim risus, sodales in pellentesque eget, sagittis sit amet mi. Phasellus at mollis dolor. Etiam turpis nunc, suscipit eget tincidunt aliquet, accumsan non lectus. Nulla facilisi. Phasellus sed lorem quis mauris adipiscing elementum. Donec nec massa ligula. Quisque iaculis nunc sed mi egestas laoreet.', 2);

INSERT INTO product (name,category,material,size,gender,price,img1,qty,description,store_id)
VALUES('jetter ring','rings','silver','medium','male',24.99,'images/Default_Pic.png',10,'Nam placerat, elit eu venenatis bibendum, diam turpis consequat eros, eget cursus massa ligula in orci. Sed imperdiet tortor nec dui porta sed pharetra quam aliquam. Pellentesque a nisl lorem. Nunc gravida interdum risus, sit amet tincidunt lacus commodo ac. Suspendisse aliquet odio sed tellus tempor placerat. Etiam hendrerit nisl sit amet neque pulvinar ornare. Maecenas elit justo, elementum ut vestibulum fringilla, accumsan mollis mi. Quisque hendrerit sagittis nisl. Nunc semper porta magna. Aenean suscipit nibh et lorem vestibulum gravid', 2);

INSERT INTO product (name,category,material,size,gender,price,img1,qty,description,store_id)
VALUES('grip ring','rings','silver','medium','female',112.99,'images/Default_Pic.png',10,'Duis id malesuada augue. Nam mi erat, pretium sit amet tempor in, ultrices at augue. Sed aliquet pulvinar dignissim. Morbi bibendum sem eu nulla semper non vehicula nulla interdum. Aliquam sodales arcu in nibh ullamcorper hendrerit. Curabitur facilisis mauris id arcu volutpat congue. Nulla sit amet odio orci, quis lacinia leo. Vestibulum vel lobortis mauris. ', 2);

INSERT INTO product (name,category,material,size,gender,price,img1,qty,description,store_id)
VALUES('hyp ring','rings','silver','medium','unisex',8.99,'images/Default_Pic.png',10,'Nulla aliquet fermentum tortor nec semper. Sed justo ipsum, vehicula sed lacinia vitae, vulputate sed est. Nunc tristique quam congue neque ultricies mattis. Nunc leo sapien, porttitor quis vehicula non, bibendum sed mauris. Etiam sed lorem nisl. Nunc consectetur vestibulum tristique. Maecenas ut eros neque. Vestibulum luctus eros sed tortor commodo faucibus. Curabitur nec rhoncus turpis. Nunc aliquet interdum leo, ac tempus nisl convallis at. Phasellus sit amet velit ante.', 2);

INSERT INTO product (name,category,material,size,gender,price,img1,qty,description,store_id)
VALUES('w23c ring','rings','silver','medium','female',2.99,'images/Default_Pic.png',10,'Mauris porttitor ipsum in quam interdum imperdiet. Sed enim risus, sodales in pellentesque eget, sagittis sit amet mi. Phasellus at mollis dolor. Etiam turpis nunc, suscipit eget tincidunt aliquet, accumsan non lectus. Nulla facilisi. Phasellus sed lorem quis mauris adipiscing elementum. Donec nec massa ligula. Quisque iaculis nunc sed mi egestas laoreet.', 2);

INSERT INTO product (name,category,material,size,gender,price,img1,qty,description,store_id)
VALUES('copper ring','rings','silver','medium','male',24.99,'images/Default_Pic.png',10,'Nam placerat, elit eu venenatis bibendum, diam turpis consequat eros, eget cursus massa ligula in orci. Sed imperdiet tortor nec dui porta sed pharetra quam aliquam. Pellentesque a nisl lorem. Nunc gravida interdum risus, sit amet tincidunt lacus commodo ac. Suspendisse aliquet odio sed tellus tempor placerat. Etiam hendrerit nisl sit amet neque pulvinar ornare. Maecenas elit justo, elementum ut vestibulum fringilla, accumsan mollis mi. Quisque hendrerit sagittis nisl. Nunc semper porta magna. Aenean suscipit nibh et lorem vestibulum gravid', 2);

INSERT INTO product (name,category,material,size,gender,price,img1,qty,description,store_id)
VALUES('ring for women','rings','silver','medium','female',112.99,'images/Default_Pic.png',10,'Duis id malesuada augue. Nam mi erat, pretium sit amet tempor in, ultrices at augue. Sed aliquet pulvinar dignissim. Morbi bibendum sem eu nulla semper non vehicula nulla interdum. Aliquam sodales arcu in nibh ullamcorper hendrerit. Curabitur facilisis mauris id arcu volutpat congue. Nulla sit amet odio orci, quis lacinia leo. Vestibulum vel lobortis mauris. ', 2);

INSERT INTO product (name,category,material,size,gender,price,img1,qty,description,store_id)
VALUES('ring of time','rings','silver','medium','unisex',8.99,'images/Default_Pic.png',10,'Nulla aliquet fermentum tortor nec semper. Sed justo ipsum, vehicula sed lacinia vitae, vulputate sed est. Nunc tristique quam congue neque ultricies mattis. Nunc leo sapien, porttitor quis vehicula non, bibendum sed mauris. Etiam sed lorem nisl. Nunc consectetur vestibulum tristique. Maecenas ut eros neque. Vestibulum luctus eros sed tortor commodo faucibus. Curabitur nec rhoncus turpis. Nunc aliquet interdum leo, ac tempus nisl convallis at. Phasellus sit amet velit ante.', 2);

INSERT INTO product (name,category,material,size,gender,price,img1,qty,description,store_id)
VALUES('black ring','rings','silver','medium','female',2.99,'images/Default_Pic.png',10,'Mauris porttitor ipsum in quam interdum imperdiet. Sed enim risus, sodales in pellentesque eget, sagittis sit amet mi. Phasellus at mollis dolor. Etiam turpis nunc, suscipit eget tincidunt aliquet, accumsan non lectus. Nulla facilisi. Phasellus sed lorem quis mauris adipiscing elementum. Donec nec massa ligula. Quisque iaculis nunc sed mi egestas laoreet.', 2);

INSERT INTO product (name,category,material,size,gender,price,img1,qty,description,store_id)
VALUES('ring223','rings','silver','medium','male',24.99,'images/Default_Pic.png',10,'Nam placerat, elit eu venenatis bibendum, diam turpis consequat eros, eget cursus massa ligula in orci. Sed imperdiet tortor nec dui porta sed pharetra quam aliquam. Pellentesque a nisl lorem. Nunc gravida interdum risus, sit amet tincidunt lacus commodo ac. Suspendisse aliquet odio sed tellus tempor placerat. Etiam hendrerit nisl sit amet neque pulvinar ornare. Maecenas elit justo, elementum ut vestibulum fringilla, accumsan mollis mi. Quisque hendrerit sagittis nisl. Nunc semper porta magna. Aenean suscipit nibh et lorem vestibulum gravid', 2);

INSERT INTO product (name,category,material,size,gender,price,img1,qty,description,store_id)
VALUES('ring001','rings','silver','medium','female',112.99,'images/Default_Pic.png',10,'Duis id malesuada augue. Nam mi erat, pretium sit amet tempor in, ultrices at augue. Sed aliquet pulvinar dignissim. Morbi bibendum sem eu nulla semper non vehicula nulla interdum. Aliquam sodales arcu in nibh ullamcorper hendrerit. Curabitur facilisis mauris id arcu volutpat congue. Nulla sit amet odio orci, quis lacinia leo. Vestibulum vel lobortis mauris. ', 2);

INSERT INTO product (name,category,material,size,gender,price,img1,qty,description,store_id)
VALUES('ring998','rings','silver','medium','unisex',8.99,'images/Default_Pic.png',10,'Nulla aliquet fermentum tortor nec semper. Sed justo ipsum, vehicula sed lacinia vitae, vulputate sed est. Nunc tristique quam congue neque ultricies mattis. Nunc leo sapien, porttitor quis vehicula non, bibendum sed mauris. Etiam sed lorem nisl. Nunc consectetur vestibulum tristique. Maecenas ut eros neque. Vestibulum luctus eros sed tortor commodo faucibus. Curabitur nec rhoncus turpis. Nunc aliquet interdum leo, ac tempus nisl convallis at. Phasellus sit amet velit ante.', 2);

INSERT INTO product (name,category,material,size,gender,price,img1,qty,description,store_id)
VALUES('ring234','rings','silver','medium','female',2.99,'images/Default_Pic.png',10,'Mauris porttitor ipsum in quam interdum imperdiet. Sed enim risus, sodales in pellentesque eget, sagittis sit amet mi. Phasellus at mollis dolor. Etiam turpis nunc, suscipit eget tincidunt aliquet, accumsan non lectus. Nulla facilisi. Phasellus sed lorem quis mauris adipiscing elementum. Donec nec massa ligula. Quisque iaculis nunc sed mi egestas laoreet.', 2);

INSERT INTO product (name,category,material,size,gender,price,img1,qty,description,store_id)
VALUES('ring544','rings','silver','medium','male',24.99,'images/Default_Pic.png',10,'Nam placerat, elit eu venenatis bibendum, diam turpis consequat eros, eget cursus massa ligula in orci. Sed imperdiet tortor nec dui porta sed pharetra quam aliquam. Pellentesque a nisl lorem. Nunc gravida interdum risus, sit amet tincidunt lacus commodo ac. Suspendisse aliquet odio sed tellus tempor placerat. Etiam hendrerit nisl sit amet neque pulvinar ornare. Maecenas elit justo, elementum ut vestibulum fringilla, accumsan mollis mi. Quisque hendrerit sagittis nisl. Nunc semper porta magna. Aenean suscipit nibh et lorem vestibulum gravid', 2);

INSERT INTO product (name,category,material,size,gender,price,img1,qty,description,store_id)
VALUES('black bracelet','bracelets','wood','medium','female',112.99,'images/Default_Pic.png',10,'Duis id malesuada augue. Nam mi erat, pretium sit amet tempor in, ultrices at augue. Sed aliquet pulvinar dignissim. Morbi bibendum sem eu nulla semper non vehicula nulla interdum. Aliquam sodales arcu in nibh ullamcorper hendrerit. Curabitur facilisis mauris id arcu volutpat congue. Nulla sit amet odio orci, quis lacinia leo. Vestibulum vel lobortis mauris. ', 3);

INSERT INTO product (name,category,material,size,gender,price,img1,qty,description,store_id)
VALUES('white bracelet','bracelets','silver','medium','unisex',8.99,'images/Default_Pic.png',10,'Nulla aliquet fermentum tortor nec semper. Sed justo ipsum, vehicula sed lacinia vitae, vulputate sed est. Nunc tristique quam congue neque ultricies mattis. Nunc leo sapien, porttitor quis vehicula non, bibendum sed mauris. Etiam sed lorem nisl. Nunc consectetur vestibulum tristique. Maecenas ut eros neque. Vestibulum luctus eros sed tortor commodo faucibus. Curabitur nec rhoncus turpis. Nunc aliquet interdum leo, ac tempus nisl convallis at. Phasellus sit amet velit ante.', 3);

INSERT INTO product (name,category,material,size,gender,price,img1,qty,description,store_id)
VALUES('green bracelet','bracelets','silver','medium','female',2.99,'images/Default_Pic.png',10,'Mauris porttitor ipsum in quam interdum imperdiet. Sed enim risus, sodales in pellentesque eget, sagittis sit amet mi. Phasellus at mollis dolor. Etiam turpis nunc, suscipit eget tincidunt aliquet, accumsan non lectus. Nulla facilisi. Phasellus sed lorem quis mauris adipiscing elementum. Donec nec massa ligula. Quisque iaculis nunc sed mi egestas laoreet.', 3);

INSERT INTO product (name,category,material,size,gender,price,img1,qty,description,store_id)
VALUES('blue bracelet','bracelets','silver','medium','male',24.99,'images/Default_Pic.png',10,'Nam placerat, elit eu venenatis bibendum, diam turpis consequat eros, eget cursus massa ligula in orci. Sed imperdiet tortor nec dui porta sed pharetra quam aliquam. Pellentesque a nisl lorem. Nunc gravida interdum risus, sit amet tincidunt lacus commodo ac. Suspendisse aliquet odio sed tellus tempor placerat. Etiam hendrerit nisl sit amet neque pulvinar ornare. Maecenas elit justo, elementum ut vestibulum fbraceletilla, accumsan mollis mi. Quisque hendrerit sagittis nisl. Nunc semper porta magna. Aenean suscipit nibh et lorem vestibulum gravid', 3);

INSERT INTO product (name,category,material,size,gender,price,img1,qty,description,store_id)
VALUES('yellow bracelet','bracelets','silver','medium','female',112.99,'images/Default_Pic.png',10,'Duis id malesuada augue. Nam mi erat, pretium sit amet tempor in, ultrices at augue. Sed aliquet pulvinar dignissim. Morbi bibendum sem eu nulla semper non vehicula nulla interdum. Aliquam sodales arcu in nibh ullamcorper hendrerit. Curabitur facilisis mauris id arcu volutpat congue. Nulla sit amet odio orci, quis lacinia leo. Vestibulum vel lobortis mauris. ', 3);

INSERT INTO product (name,category,material,size,gender,price,img1,qty,description,store_id)
VALUES('orange bracelet','bracelets','silver','medium','unisex',8.99,'images/Default_Pic.png',10,'Nulla aliquet fermentum tortor nec semper. Sed justo ipsum, vehicula sed lacinia vitae, vulputate sed est. Nunc tristique quam congue neque ultricies mattis. Nunc leo sapien, porttitor quis vehicula non, bibendum sed mauris. Etiam sed lorem nisl. Nunc consectetur vestibulum tristique. Maecenas ut eros neque. Vestibulum luctus eros sed tortor commodo faucibus. Curabitur nec rhoncus turpis. Nunc aliquet interdum leo, ac tempus nisl convallis at. Phasellus sit amet velit ante.', 3);

INSERT INTO product (name,category,material,size,gender,price,img1,qty,description,store_id)
VALUES('silver bracelet','bracelets','silver','medium','female',2.99,'images/Default_Pic.png',10,'Mauris porttitor ipsum in quam interdum imperdiet. Sed enim risus, sodales in pellentesque eget, sagittis sit amet mi. Phasellus at mollis dolor. Etiam turpis nunc, suscipit eget tincidunt aliquet, accumsan non lectus. Nulla facilisi. Phasellus sed lorem quis mauris adipiscing elementum. Donec nec massa ligula. Quisque iaculis nunc sed mi egestas laoreet.', 3);

INSERT INTO product (name,category,material,size,gender,price,img1,qty,description,store_id)
VALUES('long bracelet','bracelets','silver','medium','male',24.99,'images/Default_Pic.png',10,'Nam placerat, elit eu venenatis bibendum, diam turpis consequat eros, eget cursus massa ligula in orci. Sed imperdiet tortor nec dui porta sed pharetra quam aliquam. Pellentesque a nisl lorem. Nunc gravida interdum risus, sit amet tincidunt lacus commodo ac. Suspendisse aliquet odio sed tellus tempor placerat. Etiam hendrerit nisl sit amet neque pulvinar ornare. Maecenas elit justo, elementum ut vestibulum fbraceletilla, accumsan mollis mi. Quisque hendrerit sagittis nisl. Nunc semper porta magna. Aenean suscipit nibh et lorem vestibulum gravid', 3);

INSERT INTO product (name,category,material,size,gender,price,img1,qty,description,store_id)
VALUES('short bracelet','bracelets','silver','medium','female',112.99,'images/Default_Pic.png',10,'Duis id malesuada augue. Nam mi erat, pretium sit amet tempor in, ultrices at augue. Sed aliquet pulvinar dignissim. Morbi bibendum sem eu nulla semper non vehicula nulla interdum. Aliquam sodales arcu in nibh ullamcorper hendrerit. Curabitur facilisis mauris id arcu volutpat congue. Nulla sit amet odio orci, quis lacinia leo. Vestibulum vel lobortis mauris. ', 3);

INSERT INTO product (name,category,material,size,gender,price,img1,qty,description,store_id)
VALUES('cat bracelet','bracelets','silver','medium','unisex',8.99,'images/Default_Pic.png',10,'Nulla aliquet fermentum tortor nec semper. Sed justo ipsum, vehicula sed lacinia vitae, vulputate sed est. Nunc tristique quam congue neque ultricies mattis. Nunc leo sapien, porttitor quis vehicula non, bibendum sed mauris. Etiam sed lorem nisl. Nunc consectetur vestibulum tristique. Maecenas ut eros neque. Vestibulum luctus eros sed tortor commodo faucibus. Curabitur nec rhoncus turpis. Nunc aliquet interdum leo, ac tempus nisl convallis at. Phasellus sit amet velit ante.', 3);

INSERT INTO product (name,category,material,size,gender,price,img1,qty,description,store_id)
VALUES('dog bracelet','bracelets','silver','medium','female',2.99,'images/Default_Pic.png',10,'Mauris porttitor ipsum in quam interdum imperdiet. Sed enim risus, sodales in pellentesque eget, sagittis sit amet mi. Phasellus at mollis dolor. Etiam turpis nunc, suscipit eget tincidunt aliquet, accumsan non lectus. Nulla facilisi. Phasellus sed lorem quis mauris adipiscing elementum. Donec nec massa ligula. Quisque iaculis nunc sed mi egestas laoreet.', 3);

INSERT INTO product (name,category,material,size,gender,price,img1,qty,description,store_id)
VALUES('jetter bracelet','bracelets','silver','medium','male',24.99,'images/Default_Pic.png',10,'Nam placerat, elit eu venenatis bibendum, diam turpis consequat eros, eget cursus massa ligula in orci. Sed imperdiet tortor nec dui porta sed pharetra quam aliquam. Pellentesque a nisl lorem. Nunc gravida interdum risus, sit amet tincidunt lacus commodo ac. Suspendisse aliquet odio sed tellus tempor placerat. Etiam hendrerit nisl sit amet neque pulvinar ornare. Maecenas elit justo, elementum ut vestibulum fbraceletilla, accumsan mollis mi. Quisque hendrerit sagittis nisl. Nunc semper porta magna. Aenean suscipit nibh et lorem vestibulum gravid', 3);

INSERT INTO product (name,category,material,size,gender,price,img1,qty,description,store_id)
VALUES('grip bracelet','bracelets','silver','medium','female',112.99,'images/Default_Pic.png',10,'Duis id malesuada augue. Nam mi erat, pretium sit amet tempor in, ultrices at augue. Sed aliquet pulvinar dignissim. Morbi bibendum sem eu nulla semper non vehicula nulla interdum. Aliquam sodales arcu in nibh ullamcorper hendrerit. Curabitur facilisis mauris id arcu volutpat congue. Nulla sit amet odio orci, quis lacinia leo. Vestibulum vel lobortis mauris. ', 3);

INSERT INTO product (name,category,material,size,gender,price,img1,qty,description,store_id)
VALUES('hyp bracelet','bracelets','silver','medium','unisex',8.99,'images/Default_Pic.png',10,'Nulla aliquet fermentum tortor nec semper. Sed justo ipsum, vehicula sed lacinia vitae, vulputate sed est. Nunc tristique quam congue neque ultricies mattis. Nunc leo sapien, porttitor quis vehicula non, bibendum sed mauris. Etiam sed lorem nisl. Nunc consectetur vestibulum tristique. Maecenas ut eros neque. Vestibulum luctus eros sed tortor commodo faucibus. Curabitur nec rhoncus turpis. Nunc aliquet interdum leo, ac tempus nisl convallis at. Phasellus sit amet velit ante.', 3);

INSERT INTO product (name,category,material,size,gender,price,img1,qty,description,store_id)
VALUES('w23c bracelet','bracelets','silver','medium','female',2.99,'images/Default_Pic.png',10,'Mauris porttitor ipsum in quam interdum imperdiet. Sed enim risus, sodales in pellentesque eget, sagittis sit amet mi. Phasellus at mollis dolor. Etiam turpis nunc, suscipit eget tincidunt aliquet, accumsan non lectus. Nulla facilisi. Phasellus sed lorem quis mauris adipiscing elementum. Donec nec massa ligula. Quisque iaculis nunc sed mi egestas laoreet.', 3);

INSERT INTO product (name,category,material,size,gender,price,img1,qty,description,store_id)
VALUES('copper bracelet','bracelets','silver','medium','male',24.99,'images/Default_Pic.png',10,'Nam placerat, elit eu venenatis bibendum, diam turpis consequat eros, eget cursus massa ligula in orci. Sed imperdiet tortor nec dui porta sed pharetra quam aliquam. Pellentesque a nisl lorem. Nunc gravida interdum risus, sit amet tincidunt lacus commodo ac. Suspendisse aliquet odio sed tellus tempor placerat. Etiam hendrerit nisl sit amet neque pulvinar ornare. Maecenas elit justo, elementum ut vestibulum fbraceletilla, accumsan mollis mi. Quisque hendrerit sagittis nisl. Nunc semper porta magna. Aenean suscipit nibh et lorem vestibulum gravid', 3);

INSERT INTO product (name,category,material,size,gender,price,img1,qty,description,store_id)
VALUES('bracelet for women','bracelets','silver','medium','female',112.99,'images/Default_Pic.png',10,'Duis id malesuada augue. Nam mi erat, pretium sit amet tempor in, ultrices at augue. Sed aliquet pulvinar dignissim. Morbi bibendum sem eu nulla semper non vehicula nulla interdum. Aliquam sodales arcu in nibh ullamcorper hendrerit. Curabitur facilisis mauris id arcu volutpat congue. Nulla sit amet odio orci, quis lacinia leo. Vestibulum vel lobortis mauris. ', 3);

INSERT INTO product (name,category,material,size,gender,price,img1,qty,description,store_id)
VALUES('bracelet of time','bracelets','silver','medium','unisex',8.99,'images/Default_Pic.png',10,'Nulla aliquet fermentum tortor nec semper. Sed justo ipsum, vehicula sed lacinia vitae, vulputate sed est. Nunc tristique quam congue neque ultricies mattis. Nunc leo sapien, porttitor quis vehicula non, bibendum sed mauris. Etiam sed lorem nisl. Nunc consectetur vestibulum tristique. Maecenas ut eros neque. Vestibulum luctus eros sed tortor commodo faucibus. Curabitur nec rhoncus turpis. Nunc aliquet interdum leo, ac tempus nisl convallis at. Phasellus sit amet velit ante.', 3);

INSERT INTO product (name,category,material,size,gender,price,img1,qty,description,store_id)
VALUES('black bracelet','bracelets','silver','medium','female',2.99,'images/Default_Pic.png',10,'Mauris porttitor ipsum in quam interdum imperdiet. Sed enim risus, sodales in pellentesque eget, sagittis sit amet mi. Phasellus at mollis dolor. Etiam turpis nunc, suscipit eget tincidunt aliquet, accumsan non lectus. Nulla facilisi. Phasellus sed lorem quis mauris adipiscing elementum. Donec nec massa ligula. Quisque iaculis nunc sed mi egestas laoreet.', 3);

INSERT INTO product (name,category,material,size,gender,price,img1,qty,description,store_id)
VALUES('bracelet223','bracelets','silver','medium','male',24.99,'images/Default_Pic.png',10,'Nam placerat, elit eu venenatis bibendum, diam turpis consequat eros, eget cursus massa ligula in orci. Sed imperdiet tortor nec dui porta sed pharetra quam aliquam. Pellentesque a nisl lorem. Nunc gravida interdum risus, sit amet tincidunt lacus commodo ac. Suspendisse aliquet odio sed tellus tempor placerat. Etiam hendrerit nisl sit amet neque pulvinar ornare. Maecenas elit justo, elementum ut vestibulum fbraceletilla, accumsan mollis mi. Quisque hendrerit sagittis nisl. Nunc semper porta magna. Aenean suscipit nibh et lorem vestibulum gravid', 3);

INSERT INTO product (name,category,material,size,gender,price,img1,qty,description,store_id)
VALUES('bracelet001','bracelets','silver','medium','female',112.99,'images/Default_Pic.png',10,'Duis id malesuada augue. Nam mi erat, pretium sit amet tempor in, ultrices at augue. Sed aliquet pulvinar dignissim. Morbi bibendum sem eu nulla semper non vehicula nulla interdum. Aliquam sodales arcu in nibh ullamcorper hendrerit. Curabitur facilisis mauris id arcu volutpat congue. Nulla sit amet odio orci, quis lacinia leo. Vestibulum vel lobortis mauris. ', 3);

INSERT INTO product (name,category,material,size,gender,price,img1,qty,description,store_id)
VALUES('bracelet998','bracelets','silver','medium','unisex',8.99,'images/Default_Pic.png',10,'Nulla aliquet fermentum tortor nec semper. Sed justo ipsum, vehicula sed lacinia vitae, vulputate sed est. Nunc tristique quam congue neque ultricies mattis. Nunc leo sapien, porttitor quis vehicula non, bibendum sed mauris. Etiam sed lorem nisl. Nunc consectetur vestibulum tristique. Maecenas ut eros neque. Vestibulum luctus eros sed tortor commodo faucibus. Curabitur nec rhoncus turpis. Nunc aliquet interdum leo, ac tempus nisl convallis at. Phasellus sit amet velit ante.', 3);

INSERT INTO product (name,category,material,size,gender,price,img1,qty,description,store_id)
VALUES('bracelet234','bracelets','silver','medium','female',2.99,'images/Default_Pic.png',10,'Mauris porttitor ipsum in quam interdum imperdiet. Sed enim risus, sodales in pellentesque eget, sagittis sit amet mi. Phasellus at mollis dolor. Etiam turpis nunc, suscipit eget tincidunt aliquet, accumsan non lectus. Nulla facilisi. Phasellus sed lorem quis mauris adipiscing elementum. Donec nec massa ligula. Quisque iaculis nunc sed mi egestas laoreet.', 3);

INSERT INTO product (name,category,material,size,gender,price,img1,qty,description,store_id)
VALUES('bracelet544','bracelets','silver','medium','male',24.99,'images/Default_Pic.png',10,'Nam placerat, elit eu venenatis bibendum, diam turpis consequat eros, eget cursus massa ligula in orci. Sed imperdiet tortor nec dui porta sed pharetra quam aliquam. Pellentesque a nisl lorem. Nunc gravida interdum risus, sit amet tincidunt lacus commodo ac. Suspendisse aliquet odio sed tellus tempor placerat. Etiam hendrerit nisl sit amet neque pulvinar ornare. Maecenas elit justo, elementum ut vestibulum fbraceletilla, accumsan mollis mi. Quisque hendrerit sagittis nisl. Nunc semper porta magna. Aenean suscipit nibh et lorem vestibulum gravid', 3);
